---
# Variable setup.
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

# Enable Aegir to access as a remote user.

- name: Symbolic link to Aegir's NGINX Config
  file:
    src: "{{ aegir_user_home }}/config/nginx.conf"
    dest: "{{ nginx_conf_path }}/aegir.conf"
    state: link
    force: yes

- name: Add aegir user to sudoers to reload NGINX
  lineinfile:
    dest: '{{ sudoers_file_path }}'
    regexp: '^{{ item }}'
    line: '{{ item }} ALL=NOPASSWD: {{ nginx_control }}'
    state: present
    validate: 'visudo -cf %s'
    create: yes
  with_items:
    - aegir

- name: Add aegir to nginx group.
  when: aegir_user_in_web_group == 'yes'
  user:
    name: "{{ aegir_user_name }}"
    groups: "{{ nginx_user }}"
    append: yes

- name: Remove conflicting configuration from Geerlingguy's template.    server_names_hash_bucket_size 64;
  lineinfile:
    dest: '{{ nginx_conf_file_path }}'
    line: '{{ item }}'
    state: absent
  with_items:
    - "    server_names_hash_bucket_size 64;"
    - "    log_format  main  '$remote_addr - $remote_user [$time_local] \"$request\" '"
    - "                      '$status $body_bytes_sent \"$http_referer\" '"
    - "                      '\"$http_user_agent\" \"$http_x_forwarded_for\"';"
    - "    access_log  {{ nginx_access_log }};"

